language: node_js
node_js:
  - "10"
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  before_deploy:
    - npm run build
  on:
    tags: true
    branch: master
